//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EstructuraDatos.rc
//
#define IDD_Login                       101
#define IDD_WLogin                      101
#define IDD_WPrincipal                  103
#define IDD_WEspecial                   105
#define IDD_WMedicos                    107
#define IDD_WPaciente                   109
#define IDD_WCitas                      111
#define IDD_WMostrarCitas               114
#define IDC_UsuarioL                    1001
#define IDC_ContraL                     1002
#define IDC_Entrar                      1003
#define IDC_ContraML                    1004
#define IDC_MostrarL                    1006
#define IDC_NoMostrarL                  1007
#define IDC_Mostrar                     1008
#define IDC_NombreMedico                1009
#define IDC_ToEspecial                  1010
#define IDC_MedicoBu                    1010
#define IDC_IDEspecial                  1011
#define IDC_NomEspecial                 1012
#define IDC_BorrarEspecial              1013
#define IDC_ModEspecial                 1014
#define IDC_AgregarEspecial             1015
#define IDC_DesEspecial                 1016
#define IDC_NombreUs                    1017
#define IDC_MostrarEsp                  1018
#define IDC_CedulaMedico                1019
#define IDC_NumeroMedico                1020
#define IDC_COMBODias                   1021
#define IDC_DiasTrabajo                 1022
#define IDC_COMBOHoraI                  1023
#define IDC_HorasTrabajo                1024
#define IDC_AgregarFoto                 1025
#define IDC_GuardarMedico               1026
#define IDC_Medicos                     1027
#define IDC_ReferenciaPaciente          1027
#define IDC_COMBOEsp                    1027
#define IDC_Especialidad                1028
#define IDC_NumeroPaciente              1028
#define IDC_COMBOCons                   1028
#define IDC_EdadPaciente                1029
#define IDC_EditMedico                  1029
#define IDC_Femenino                    1030
#define IDC_COMBOHoras2                 1030
#define IDC_COMBOHoraF                  1030
#define IDC_Masculino                   1031
#define IDC_EliminarMed                 1031
#define IDC_SeleFoto                    1032
#define IDC_FechaNacimiento             1033
#define IDC_Paciente                    1034
#define IDC_PrimerMedico                1034
#define IDC_Citas                       1035
#define IDC_Lunes                       1035
#define IDC_Martes                      1036
#define IDC_Miercoles                   1037
#define IDC_Jueves                      1038
#define IDC_Viernes                     1039
#define IDC_Sabado                      1040
#define IDC_Domingo                     1041
#define IDC_BuscarMed                   1042
#define IDC_GuardarPacien               1043
#define IDC_ApellidosPacien             1044
#define IDC_SelectFecha                 1045
#define IDC_NombrePaciente              1046
#define IDC_COMBEsp                     1047
#define IDC_COMBMedico                  1048
#define IDC_Select                      1049
#define IDC_COMBPaciente                1050
#define IDC_COMBOHoraCita               1051
#define IDC_SelMedico                   1052
#define IDC_GuardarCita                 1053
#define IDC_Picture                     1054
#define IDC_SelectPaciente              1055
#define IDC_TelefonoP                   1056
#define IDC_DATETIMEPICKERF             1058
#define IDC_Consult                     1059
#define IDC_ClaveCita                   1060
#define IDC_BuscarCita                  1061
#define IDC_LISTCitas                   1064
#define IDC_MedMes                      1065
#define IDC_EspSemana                   1066
#define IDC_TodasSem                    1067
#define IDC_MostrarCitas                1069
#define IDC_Seleccionar                 1070
#define IDC_DATETIMEPICKERCitas         1071
#define IDC_SeleccionarF                1072
#define IDC_STATICEleg                  1073
#define IDC_MedicoID                    1074
#define IDC_STATICCedula                1075
#define IDC_COMBEspecial                1076
#define IDC_ClaveUsuario                1077
#define IDC_EditCita                    1080
#define IDC_CancelarStatic              1081
#define IDC_CancelarText                1082
#define IDC_MedicoFoto                  1083
#define IDC_RADIOPendiente              1084
#define IDC_RADIOAtendida               1085
#define IDC_CancelarCita                1086
#define IDC_SeleccionarRegistro         1087
#define IDC_FotoMedicoC                 1088
#define IDC_FotoMedicoCi                1088
#define IDC_NombreError                 1089
#define IDC_NumeroError                 1090
#define IDC_CedulaError                 1091
#define IDC_EspecialidadError           1092
#define IDC_DiasError                   1093
#define IDC_ConsultorioError            1094
#define IDC_HorasError                  1095
#define IDC_FotoError                   1096
#define IDC_ApellidosError              1097
#define IDC_GeneroError                 1098
#define IDC_EdadError                   1099
#define IDC_FechaPError                 1100
#define IDC_RefError                    1101
#define IDC_NMedError                   1102
#define IDC_NombrePError                1103
#define IDC_NumeroPError                1104
#define IDC_PacError                    1105
#define IDC_MedError                    1106
#define IDC_FechaCError                 1107
#define IDC_HoraCError                  1108
#define IDC_IDError                     1109
#define IDC_NEspError                   1110
#define IDC_DesEspError                 1111
#define IDC_EditPac                     1112
#define IDC_BuscarPa                    1113
#define IDC_BBuscarPa                   1114
#define IDC_EliminarPa                  1115
#define IDC_BuscarPaN                   1116
#define IDC_FotoInicio                  1117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
